#!/usr/bin/env python3
import subprocess
import sys
from openai import OpenAI
from dotenv import load_dotenv
import os
import shlex
import time
import threading
import itertools
import configparser
import argparse

load_dotenv()

def menu():
    parser = argparse.ArgumentParser(description='Vow CLI Tool')
    parser.add_argument('-reset', action='store_true', help='Reset the stored API key to default')
    parser.add_argument('-show', action='store_true', help='Show the current API key')
    parser.add_argument('-model', action='store_true', help='Change the GPT model')
    parser.add_argument('command', nargs=argparse.REMAINDER, help='Command to ask for GPT model')

    args = parser.parse_args()

    if args.reset:
        delete_api_key()
        print("API key reseted.")
        exit()
    
    if args.show:
        api_key = get_api_key()
        if len(api_key) == 0:
            print("No API key found.")
        else:
            print(api_key)
        exit()

    if args.model:
        model = get_model()
        switch_model()
        exit()

def get_api_key():
    # First, try to get the API key from an environment variable
    api_key = os.getenv('OPENAI_API_KEY')

    if not api_key:
        # If not found in environment, try to get it from a config file
        config = configparser.ConfigParser()
        config.read('config.ini')

        if 'openai' in config and 'api_key' in config['openai']:
            api_key = config['openai']['api_key']
        else:
            # If not found in config, prompt the user to enter it
            api_key = input("Enter your OpenAI API key: ")

            # Optional: Save the entered API key to a config file for future use
            save = input("Do you want to save this API key for future use? (y/n): ").lower()
            if save == 'y':
                config['openai'] = {'api_key': api_key}
                with open('config.ini', 'w') as configfile:
                    config.write(configfile)

    return api_key

def delete_api_key():
    config = configparser.ConfigParser()
    config.read('config.ini')
    config['openai'] = {'api_key': ""}
    with open('config.ini', 'w') as configfile:
        config.write(configfile)

def get_model():
    # First, try to get the API key from an environment variable
    model = os.getenv('GPT_MODEL')

    if not model:
        # If not found in environment, try to get it from a config file
        config = configparser.ConfigParser()
        config.read('config.ini')

        if 'openai' in config and 'model' in config['openai']:
            model = config['openai']['model']
        else:
            # If not found in config, prompt the user to enter it
            model = input("Enter your OpenAI model(ex. gpt-3.5-turbo, gpt-4): ")

            # Optional: Save the entered API key to a config file for future use
            save = input("Do you want to save this model for future use? (y/n): ").lower()
            if save == 'y':
                config['openai'] = {'model': model}
                with open('config.ini', 'w') as configfile:
                    config.write(configfile)

    return model

def switch_model():
    config = configparser.ConfigParser()
    config.read('config.ini')
    # print the current model
    print("Current model is: " + config['openai']['model'])
    # check if the user wants to change the model
    print("Do you want to change the model? (y/n)")
    if input() == "y":
        # prompt the user to enter it
        model = input("Enter your OpenAI model(ex. gpt-3.5-turbo, gpt-4): ")
        # Optional: Save the entered API key to a config file for future use
        save = input("Do you want to save this model for future use? (y/n): ").lower()
        if save == 'y':
            config['openai'] = {'model': model}
            with open('config.ini', 'w') as configfile:
                config.write(configfile)
        print("Model changed.")
    


def spinner(stop_event):
    for cursor in itertools.cycle('|/-\\'):
        if stop_event.is_set():
            break
        sys.stdout.write(cursor)
        sys.stdout.flush()
        sys.stdout.write('\b')
        time.sleep(0.1)

def run_command(command):
    try:
        # Run the command and capture output
        result = subprocess.run(command, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error: {e.stderr}")

def get_input():
    command = ""
    if len(sys.argv) > 1:
        command = shlex.join(sys.argv[1:])
        return command
    else:
        print("No command provided.")
        return None

def main():
    menu()
    api_key = get_api_key()
    model = get_model()
    
    client = OpenAI(
        api_key=api_key,
        # api_key= os.getenv("OPENAI_API_KEY"),
    )

    user_input = get_input()
    if user_input is not None and "exit" in user_input.split():
        exit()

    raw_input = "Give me the command to run:" + user_input + "in MacOS terminal, give me the output directly without any explaination in one line."
    stop_event = threading.Event()
    spinner_thread = threading.Thread(target=spinner, args=(stop_event,))
    spinner_thread.start()

    try:
        completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": raw_input,
                }
            ],
            model=model,
        )
        raw_output = completion.choices[0].message.content
    except Exception as e:
        print(f"API error: {e}")
        return
    
    stop_event.set()
    spinner_thread.join()
    
    print("The following command will run: ")
    print("================================")
    print(raw_output)
    print("================================")
    print("Are you sure to run? (y/n)")
    if input() == "y":
        print("Here is the result after running:")
        print("================================")
        run_command(raw_output)
        # check if raw_output contains "rm"
        if "rm" in raw_output.split():
            print("Remove excuted.")
    else:
        print("================================")
        print("Command cancelled.")

if __name__ == "__main__":
    main()